package Cars;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;


public class  IAmSoAngry {

  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

//NumberPlateFinder charlie = new NumberPlateFinder();
//charlie.getNumbers;


  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }


  public void tearDown() {
    driver.quit();
  }


  public void iAmSoAngry(String input) {
    String[] output = new String[5];
    output[0] =input;

    driver.get("https://cartaxcheck.co.uk/");
    driver.manage().window().setSize(new Dimension(1936, 1096));
    driver.findElement(By.id("vrm-input")).click();
    driver.findElement(By.id("vrm-input")).sendKeys(input);
    driver.findElement(By.cssSelector(".jsx-1164392954")).click();

    {
      WebElement element = driver.findElement(By.cssSelector(".lds-ellipsis"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".jsx-497547138:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".jsx-3517272246:nth-child(1) > .jsx-3496807389")).click();
    driver.findElement(By.cssSelector(".jsx-3499070155:nth-child(2) > .jsx-3517272246:nth-child(2)")).click();
    driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
    {
      WebElement element = driver.findElement(By.xpath("//dl[2]/dd"));
      String make = element.getText();
      output[1] = make;
    }
;
    {
      WebElement element = driver.findElement(By.xpath("//dl[3]/dd"));
      String model = element.getText();
      output[2] = model;

    }
    {
      WebElement element = driver.findElement(By.xpath("//dl[4]/dd"));
      String colour = element.getText();
      output[3] = colour;
    }
    {
      WebElement element = driver.findElement(By.xpath("//dl[5]/dd"));
      String year = element.getText();
      output[4] = year;
    }
    driver.findElement(By.cssSelector(".jsx-3499070155:nth-child(2) > .jsx-3517272246:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".jsx-3517272246:nth-child(4) > .jsx-3496807389")).click();
    driver.close();
  }
}
